### ISSUE TITLE
Rosetta tests are flaky

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/stacks-blockchain-api#1077]
The `test-rosetta` suite is flaky at times, for example: https://github.com/hirosystems/stacks-blockchain-api/runs/5314495421?check_suite_focus=true#step:8:2456

The error output shows
```
    console.log
      Error getting pox info on try 97 Error: Response 500: Internal Server Error fetching http://127.0.0.1:20443/v2/pox - Failed to query peer info
          at StacksCoreRpcClient.fetchText (/home/runner/work/stacks-blockchain-api/stacks-blockchain-api/src/core-rpc/client.ts:133:13)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at StacksCoreRpcClient.fetchJson (/home/runner/work/stacks-blockchain-api/stacks-blockchain-api/src/core-rpc/client.ts:112:26)
          at StacksCoreRpcClient.getPox (/home/runner/work/stacks-blockchain-api/stacks-blockchain-api/src/core-rpc/client.ts:150:20)
          at standByForPoxToBeReady (/home/runner/work/stacks-blockchain-api/stacks-blockchain-api/src/tests-rosetta/api.ts:113:9)
          at Object.<anonymous> (/home/runner/work/stacks-blockchain-api/stacks-blockchain-api/src/tests-rosetta/api.ts:3076:5)

      at standByForPoxToBeReady (tests-rosetta/api.ts:117:17)
          at runMicrotasks (<anonymous>)
```

This could be due to the way those tests are crafted, by running an Event Server in parallel to the tests and thus being susceptible to timing or race conditions.

Usually, re-running all jobs from Github actions fixes the issue temporarily.

**Comment by MHassanTariq** [comment]
@rafaelcr do you recommend updating db manually with data to test? That will remove the integration in tests. We can use this approach for all tests other than construction apis. We might have to consider writing those tests separately. 
An example is in my PR [here](https://github.com/hirosystems/stacks-blockchain-api/pull/1072/files#diff-cb5a6340146571d0092cd38e8d8516f087e054d3730aa7bd67636649a4f30fd8R3292-R3511).
