### ISSUE TITLE
API failed due to failing to deserialize a mempool tx

### ISSUE THREAD

**Issue by aulneau** [hirosystems/stacks-blockchain-api#1181]
Running v4.0.0-beta.3, stalled at block height 61312
```json
{
  "level": "error",
  "message": "Error processing core node mempool message Failed to decode transaction: DeserializeError { error: \"Failed to deserialize contract name: too short or too long: 43\" }\n",
  "stack": "Error: Failed to decode transaction: DeserializeError { error: \"Failed to deserialize contract name: too short or too long: 43\" }\n\n at stacks_encoding_native_js::stacks_tx::decode_transaction (<anonymous>)\n at /app/src/event-stream/event-server.ts:137:39\n at Array.map (<anonymous>)\n at handleMempoolTxsMessage (/app/src/event-stream/event-server.ts:136:35)\n at /app/src/event-stream/event-server.ts:713:20\n at run (/app/node_modules/p-queue/dist/index.js:157:104)\n at PQueue._tryToStartAnother (/app/node_modules/p-queue/dist/index.js:105:17)\n at /app/node_modules/p-queue/dist/index.js:171:18\n at new Promise (<anonymous>)\n at PQueue.add (/app/node_modules/p-queue/dist/index.js:152:16)\n at Object.handleMempoolTxs (/app/src/event-stream/event-server.ts:713:10)\n at /app/src/event-stream/event-server.ts:846:30\n at asyncUtilWrap (/app/src/api/async-handler.ts:32:24)\n at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n at next (/app/node_modules/express/lib/router/route.js:137:13)\n at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)",
  "timestamp": "2022-05-25T13:55:42.661Z"
}
```

**Comment by rafaelcr** [comment]
Thanks @aulneau we also saw that and are currently working on a fix to deploy ASAP
