### ISSUE TITLE
Possible regression in 4.0.0

### ISSUE THREAD

**Issue by wileyj** [hirosystems/stacks-blockchain-api#1188]
using the following endpoint: `/rosetta/v1/block`

Several known API nodes running 4.0.0 have the following error with block `61644`:
```
➭ curl -L -H "Content-Type: application/json" \
 -d '{
    "network_identifier": {
        "blockchain": "stacks",
        "network": "mainnet"
    },
    "block_identifier": {
        "index": "61644"
    }
}' \
https://stacks-node-api.mainnet.stacks.co/rosetta/v1/block
{
  "error": "TypeError: Cannot read properties of undefined (reading 'name')",
  "stack": "TypeError: Cannot read properties of undefined (reading 'name')\n    at /app/src/rosetta-helpers.ts:804:77\n    at Array.find (<anonymous>)\n    at parseDelegateStxArgs (/app/src/rosetta-helpers.ts:804:65)\n    at parseStackingContractCall (/app/src/rosetta-helpers.ts:727:14)\n    at makeCallContractOperation (/app/src/rosetta-helpers.ts:592:9)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at getOperations (/app/src/rosetta-helpers.ts:138:23)\n    at parseRosettaTxDetail (/app/src/api/controllers/db-controller.ts:507:22)\n    at getRosettaBlockTransactionsFromDataStore (/app/src/api/controllers/db-controller.ts:577:23)\n    at getRosettaBlockFromDataStore (/app/src/api/controllers/db-controller.ts:334:16)\n    at /app/src/api/routes/rosetta/block.ts:33:21",
  "errorTag": "ad29a3fb-dcad-4776-8d3a-c9e6b26b949e"
}% 
```

However, using a previous version of the API (3.0.3) produces the expected output:
```
✓ ➭ curl -L -H "Content-Type: application/json" \
 -d '{
    "network_identifier": {
        "blockchain": "stacks",
        "network": "mainnet"
    },
    "block_identifier": {
        "index": "61644"
    }
}' \
https://api.stacks.org/rosetta/v1/block  
{
  "block": {
    "block_identifier": {
      "index": 61644,
      "hash": "0x1b77396dbbd3fc846f2aec94d13535e743d3a6766b725096ff46b0f3aaf9f1c2"
    },
    "parent_block_identifier": {
      "index": 61643,
      "hash": "0xf49a4a99ad0ca14dcf8a3b074fe4e1262b60a723c29b88f75bd87a24ed109633"
    },
    "timestamp": 1653692226000,
    "transactions": [
      {
...
```

This seems like a regression, or possibly something off in the event-replay upgrading to 4.0.0?

**Comment by rafaelcr** [comment]
Thanks @wileyj , I suspect this has to do with how we deal with `null` arguments when calling a function with optional parameters. I'll look into it ASAP
