### ISSUE TITLE
Development instructions in readme aren't working

### ISSUE THREAD

**Issue by mcintyre94** [hirosystems/stacks-blockchain-api#1196]
**Describe the bug**

I'm getting an error when running `npm run dev:integrated` or `npm run devenv:deploy`:

```
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[61022] Failed to execute script docker-compose
```

**To Reproduce**
1. Clone the repo
2. Run `npm run dev:integrated` or `npm run devenv:deploy`
3. See error:
`$ npm run dev:integrated`
<details>
  <summary>Click to view output/error</summary>
  
```

> @hirosystems/stacks-blockchain-api@1.0.0 dev:integrated
> npm run devenv:build && concurrently npm:dev npm:devenv:deploy


> @hirosystems/stacks-blockchain-api@1.0.0 devenv:build
> docker-compose -f docker/docker-compose.dev.postgres.yml -f docker/docker-compose.dev.stacks-blockchain.yml -f docker/docker-compose.dev.bitcoind.yml -f docker/docker-compose.dev.rosetta-cli.yml build --no-cache

WARNING: The CMD variable is not set. Defaulting to a blank string.
WARNING: The OUTPUT variable is not set. Defaulting to a blank string.
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 670, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 439, in send
  File "urllib3/connectionpool.py", line 726, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 670, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 200, in perform_command
  File "compose/cli/command.py", line 60, in project_from_options
  File "compose/cli/command.py", line 152, in get_project
  File "compose/cli/docker_client.py", line 41, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 221, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[61410] Failed to execute script docker-compose
```
</details>

I get the same error if I run `npm run devenv:deploy` or `docker-compose -f docker/docker-compose.dev.postgres.yml -f docker/docker-compose.dev.stacks-blockchain.yml -f docker/docker-compose.dev.bitcoind.yml -f docker/docker-compose.dev.rosetta-cli.yml build --no-cache`

**Expected behavior**

From the readme it sounds like these should be running the services

**Screenshots**
N/A

**Console log**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS 12.3.1 (M1 Pro) 
 - Browser: N/A
 - Version: N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by rafaelcr** [comment]
@mcintyre94 we use `npm run devenv:deploy` constantly in our CI and local dev setups and haven't had any issues. Could there be a problem with your python installation? It seems to have trouble finding `docker-compose`... maybe it's missing on `$PATH`?
