### ISSUE TITLE
Error: [mobx] There are multiple, different versions of MobX active

### ISSUE THREAD

**Issue by wileyj** [hirosystems/stacks-blockchain-api#1202]
Building the API using docker, independent of arch or libc, the following error occurs:
```
...
> @stacks/stacks-blockchain-api-types@0.1.0 generate:docs
> redoc-cli bundle --output .tmp/index.html .tmp/openapi.resolved.yaml

/src/docs/node_modules/mobx/lib/mobx.js:20
        throw new Error("[mobx] " + (message || OBFUSCATED_ERROR));
        ^

Error: [mobx] There are multiple, different versions of MobX active. Make sure MobX is loaded only once or use `configure({ isolateGlobalState: true })`
    at invariant (/src/docs/node_modules/mobx/lib/mobx.js:20:15)
    at fail (/src/docs/node_modules/mobx/lib/mobx.js:15:5)
    at Timeout._onTimeout (/src/docs/node_modules/mobx/lib/mobx.js:1487:17)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
ERROR: "generate:docs" exited with 1.
```

**Comment by zone117x** [comment]
Gotta love npm lib authors breaking semver
