### ISSUE TITLE
Bug in Rosetta endpoint for block parsing

### ISSUE THREAD

**Issue by zone117x** [hirosystems/stacks-blockchain-api#1256]
Stack trace:
```
{"level":"error","message":"HTTP POST /rosetta/v1/block","req":{"headers":{"accept-encoding":"gzip","connection":"close","content-length":"141","content-type":"application/json; charset=utf-8","host":"172.31.20.180:3999","user-agent":"okhttp/3.8.1","x-amzn-trace-id":"Root=1-62eb9174-18eb4fd10420aa8f69c7213f","x-forwarded-for":"54.251.59.216","x-forwarded-port":"443","x-forwarded-proto":"https"},"httpVersion":"1.0","method":"POST","originalUrl":"/rosetta/v1/block","query":{},"url":"/rosetta/v1/block"},"res":{"statusCode":500},"responseTime":27,"timestamp":"2022-08-04T09:29:24.681Z"}
{"date":"Thu Aug 04 2022 09:29:24 GMT+0000 (Coordinated Universal Time)","error":{"errorTag":"b402827b-769c-415d-9ba8-5465b8ce020b"},"exception":true,"level":"error","message":"middlewareError","req":{"headers":{"accept-encoding":"gzip","connection":"close","content-length":"141","content-type":"application/json; charset=utf-8","host":"172.31.20.180:3999","user-agent":"okhttp/3.8.1","x-amzn-trace-id":"Root=1-62eb9174-18eb4fd10420aa8f69c7213f","x-forwarded-for":"54.251.59.216","x-forwarded-port":"443","x-forwarded-proto":"https"},"httpVersion":"1.0","method":"POST","originalUrl":"/rosetta/v1/block","query":{},"url":"/rosetta/v1/block"},"stack":"Error: Could not find field name amount-ustx in contract call\n    at parseDelegateStxArgs (/app/src/rosetta-helpers.ts:781:11)\n    at parseStackingContractCall (/app/src/rosetta-helpers.ts:727:14)\n    at makeCallContractOperation (/app/src/rosetta-helpers.ts:592:9)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at getOperations (/app/src/rosetta-helpers.ts:138:23)\n    at parseRosettaTxDetail (/app/src/api/controllers/db-controller.ts:509:22)\n    at getRosettaBlockTransactionsFromDataStore (/app/src/api/controllers/db-controller.ts:579:23)\n    at getRosettaBlockFromDataStore (/app/src/api/controllers/db-controller.ts:335:16)\n    at /app/src/api/routes/rosetta/block.ts:33:21","timestamp":"2022-08-04T09:29:24.681Z"}
Error: Could not find field name amount-ustx in contract call
    at parseDelegateStxArgs (/app/src/rosetta-helpers.ts:781:11)
    at parseStackingContractCall (/app/src/rosetta-helpers.ts:727:14)
    at makeCallContractOperation (/app/src/rosetta-helpers.ts:592:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at getOperations (/app/src/rosetta-helpers.ts:138:23)
    at parseRosettaTxDetail (/app/src/api/controllers/db-controller.ts:509:22)
    at getRosettaBlockTransactionsFromDataStore (/app/src/api/controllers/db-controller.ts:579:23)
    at getRosettaBlockFromDataStore (/app/src/api/controllers/db-controller.ts:335:16)
    at /app/src/api/routes/rosetta/block.ts:33:21
```

* stacks-blockchain version 2.05.0.2.2
* stacks-blockchain-api version 4.1.1
* Block #70284

![image](https://user-images.githubusercontent.com/1447546/182872440-d9d43945-1df1-4a84-b5ad-ad60acdf5978.png)

**Comment by vae520283995** [comment]
> database dump https://drive.google.com/file/d/19flMAd5Q_BGVtcJ_IpLXSOGOHiUDYnYP/view?usp=sharing

@zone117x @rafaelcr 
look at this

**Comment by vae520283995** [comment]
@CharlieC3

**Comment by smcclellan** [comment]
Will not be addressed due to decreased mainteinance on Rosetta.
