### ISSUE TITLE
Smart Contracts/get_contract_by_trait returns 500

### ISSUE THREAD

**Issue by LakshmiLavanyaKasturi** [hirosystems/stacks-blockchain-api#1293]
**Describe the bug**
Smart-Contracts/operation/get_contract_by_id - throws 500 with the Json trait_abi values.

**To Reproduce**
1. Invoke https://stacks-node-api.mainnet.stacks.co/extended/v1/contract/by_trait 
2. Add query parameter with Key: trait_abi and value: "{\"maps\":[{\"key\":\"uint128\",\"name\":\"meta\",\"value\":{\"tuple\":[{\"name\":\"user\",\"type\":\"principal\"}]}},{\"key\":\"principal\",\"name\":\"owners\",\"value\":{\"tuple\":[{\"name\":\"id\",\"type\":\"uint128\"}]}}],\"functions\":[{\"args\":[{\"name\":\"value\",\"type\":\"bool\"}],\"name\":\"asserts-panic\",\"access\":\"private\",\"outputs\":{\"type\":\"bool\"}},{\"args\":[{\"name\":\"user\",\"type\":\"principal\"}],\"name\":\"mint-badge\",\"access\":\"private\",\"outputs\":{\"type\":\"bool\"}},{\"args\":[{\"name\":\"users\",\"type\":{\"list\":{\"type\":\"principal\",\"length\":5000}}},{\"name\":\"total-badges\",\"type\":\"uint128\"}],\"name\":\"mint-all\",\"access\":\"public\",\"outputs\":{\"type\":{\"response\":{\"ok\":{\"list\":{\"type\":\"bool\",\"length\":5000}},\"error\":\"uint128\"}}}},{\"args\":[],\"name\":\"get-badge-meta\",\"access\":\"read_only\",\"outputs\":{\"type\":{\"tuple\":[{\"name\":\"uri\",\"type\":{\"string-ascii\":{\"length\":78111}}}]}}},{\"args\":[],\"name\":\"get-last-id\",\"access\":\"read_only\",\"outputs\":{\"type\":\"uint128\"}},{\"args\":[{\"name\":\"user\",\"type\":\"principal\"}],\"name\":\"get-meta-by-user?\",\"access\":\"read_only\",\"outputs\":{\"type\":{\"optional\":{\"tuple\":[{\"name\":\"user\",\"type\":\"principal\"}]}}}},{\"args\":[{\"name\":\"id\",\"type\":\"uint128\"}],\"name\":\"get-meta?\",\"access\":\"read_only\",\"outputs\":{\"type\":{\"optional\":{\"tuple\":[{\"name\":\"user\",\"type\":\"principal\"}]}}}},{\"args\":[{\"name\":\"id\",\"type\":\"uint128\"}],\"name\":\"get-owner?\",\"access\":\"read_only\",\"outputs\":{\"type\":{\"optional\":\"principal\"}}}],\"variables\":[{\"name\":\"creator\",\"type\":\"principal\",\"access\":\"constant\"},{\"name\":\"last-id\",\"type\":\"uint128\",\"access\":\"variable\"},{\"name\":\"max-badges\",\"type\":\"uint128\",\"access\":\"variable\"}],\"fungible_tokens\":[],\"non_fungible_tokens\":[{\"name\":\"badge\",\"type\":\"uint128\"}]}"
3. Send API request
4. See 500 error.

**Expected behavior**
200: List of contracts implement given trait.

**Current output**
{
    "error": "TypeError: Cannot use 'in' operator to search for 'functions' in {\"maps\":[{\"key\":\"uint128\",\"name\":\"meta\",\"value\":{\"tuple\":[{\"name\":\"user\",\"type\":\"principal\"}]}},{\"key\":\"principal\",\"name\":\"owners\",\"value\":{\"tuple\":[{\"name\":\"id\",\"type\":\"uint128\"}]}}],\"functions\":[{\"args\":[{\"name\":\"value\",\"type\":\"bool\"}],\"name\":\"asserts-panic\",\"access\":\"private\",\"outputs\":{\"type\":\"bool\"}},{\"args\":[{\"name\":\"user\",\"type\":\"principal\"}],\"name\":\"mint-badge\",\"access\":\"private\",\"outputs\":{\"type\":\"bool\"}},{\"args\":[{\"name\":\"users\",\"type\":{\"list\":{\"type\":\"principal\",\"length\":5000}}},{\"name\":\"total-badges\",\"type\":\"uint128\"}],\"name\":\"mint-all\",\"access\":\"public\",\"outputs\":{\"type\":{\"response\":{\"ok\":{\"list\":{\"type\":\"bool\",\"length\":5000}},\"error\":\"uint128\"}}}},{\"args\":[],\"name\":\"get-badge-meta\",\"access\":\"read_only\",\"outputs\":{\"type\":{\"tuple\":[{\"name\":\"uri\",\"type\":{\"string-ascii\":{\"length\":78111}}}]}}},{\"args\":[],\"name\":\"get-last-id\",\"access\":\"read_only\",\"outputs\":{\"type\":\"uint128\"}},{\"args\":[{\"name\":\"user\",\"type\":\"principal\"}],\"name\":\"get-meta-by-user?\",\"access\":\"read_only\",\"outputs\":{\"type\":{\"optional\":{\"tuple\":[{\"name\":\"user\",\"type\":\"principal\"}]}}}},{\"args\":[{\"name\":\"id\",\"type\":\"uint128\"}],\"name\":\"get-meta?\",\"access\":\"read_only\",\"outputs\":{\"type\":{\"optional\":{\"tuple\":[{\"name\":\"user\",\"type\":\"principal\"}]}}}},{\"args\":[{\"name\":\"id\",\"type\":\"uint128\"}],\"name\":\"get-owner?\",\"access\":\"read_only\",\"outputs\":{\"type\":{\"optional\":\"principal\"}}}],\"variables\":[{\"name\":\"creator\",\"type\":\"principal\",\"access\":\"constant\"},{\"name\":\"last-id\",\"type\":\"uint128\",\"access\":\"variable\"},{\"name\":\"max-badges\",\"type\":\"uint128\",\"access\":\"variable\"}],\"fungible_tokens\":[],\"non_fungible_tokens\":[{\"name\":\"badge\",\"type\":\"uint128\"}]}",
    "stack": "TypeError: Cannot use 'in' operator to search for 'functions' in {\"maps\":[{\"key\":\"uint128\",\"name\":\"meta\",\"value\":{\"tuple\":[{\"name\":\"user\",\"type\":\"principal\"}]}},{\"key\":\"principal\",\"name\":\"owners\",\"value\":{\"tuple\":[{\"name\":\"id\",\"type\":\"uint128\"}]}}],\"functions\":[{\"args\":[{\"name\":\"value\",\"type\":\"bool\"}],\"name\":\"asserts-panic\",\"access\":\"private\",\"outputs\":{\"type\":\"bool\"}},{\"args\":[{\"name\":\"user\",\"type\":\"principal\"}],\"name\":\"mint-badge\",\"access\":\"private\",\"outputs\":{\"type\":\"bool\"}},{\"args\":[{\"name\":\"users\",\"type\":{\"list\":{\"type\":\"principal\",\"length\":5000}}},{\"name\":\"total-badges\",\"type\":\"uint128\"}],\"name\":\"mint-all\",\"access\":\"public\",\"outputs\":{\"type\":{\"response\":{\"ok\":{\"list\":{\"type\":\"bool\",\"length\":5000}},\"error\":\"uint128\"}}}},{\"args\":[],\"name\":\"get-badge-meta\",\"access\":\"read_only\",\"outputs\":{\"type\":{\"tuple\":[{\"name\":\"uri\",\"type\":{\"string-ascii\":{\"length\":78111}}}]}}},{\"args\":[],\"name\":\"get-last-id\",\"access\":\"read_only\",\"outputs\":{\"type\":\"uint128\"}},{\"args\":[{\"name\":\"user\",\"type\":\"principal\"}],\"name\":\"get-meta-by-user?\",\"access\":\"read_only\",\"outputs\":{\"type\":{\"optional\":{\"tuple\":[{\"name\":\"user\",\"type\":\"principal\"}]}}}},{\"args\":[{\"name\":\"id\",\"type\":\"uint128\"}],\"name\":\"get-meta?\",\"access\":\"read_only\",\"outputs\":{\"type\":{\"optional\":{\"tuple\":[{\"name\":\"user\",\"type\":\"principal\"}]}}}},{\"args\":[{\"name\":\"id\",\"type\":\"uint128\"}],\"name\":\"get-owner?\",\"access\":\"read_only\",\"outputs\":{\"type\":{\"optional\":\"principal\"}}}],\"variables\":[{\"name\":\"creator\",\"type\":\"principal\",\"access\":\"constant\"},{\"name\":\"last-id\",\"type\":\"uint128\",\"access\":\"variable\"},{\"name\":\"max-badges\",\"type\":\"uint128\",\"access\":\"variable\"}],\"fungible_tokens\":[],\"non_fungible_tokens\":[{\"name\":\"badge\",\"type\":\"uint128\"}]}\n    at parseTraitAbi (/app/src/api/query-helpers.ts:199:22)\n    at /app/src/api/routes/contract.ts:21:38\n    at asyncUtilWrap (/app/src/api/async-handler.ts:32:24)\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n    at next (/app/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n    at /app/node_modules/express/lib/router/index.js:281:22\n    at Function.process_params (/app/node_modules/express/lib/router/index.js:341:12)\n    at next (/app/node_modules/express/lib/router/index.js:275:10)\n    at Function.handle (/app/node_modules/express/lib/router/index.js:174:3)\n    at router (/app/node_modules/express/lib/router/index.js:47:12)\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/app/node_modules/express/lib/router/index.js:323:13)\n    at /app/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/app/node_modules/express/lib/router/index.js:341:12)",
    "errorTag": "80ac283f-96e3-4c74-bcc4-eb94e5cca0f9"
}

**Comment by LakshmiLavanyaKasturi** [comment]
No longer an issue. 

Eg: https://api.mainnet.hiro.so/extended/v1/contract/by_trait?trait_abi=%7B%20%22functions%22:%5B%20%7B%20%22access%22:%22read_only%22,%20%22args%22:%5B%5D,%20%22name%22:%22get-total-supply%22,%20%22outputs%22:%7B%22type%22:%20%7B%20%22response%22:%20%7B%20%22ok%22:%20%22uint128%22,%20%22error%22:%20%22uint128%22%20%7D%20%7D%20%7D%20%7D%20%5D,%20%22variables%22:%5B%5D,%20%22maps%22:%5B%5D,%20%22fungible_tokens%22:%5B%5D,%20%22non_fungible_tokens%22:%5B%5D%20%7D
