### ISSUE TITLE
Rosetta error in /block when searching by block_height

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/stacks-blockchain-api#1370]
After upgrading from 6.0.1 to 6.1.0, a user ran into this issue:
```
"message": "{\"respBody\":{\"error\":\"Error: unexpected tx not found -- could not get contract from data store\",\"stack\":\"Error: unexpected tx not found -- could not get contract from data store\\n    at makeCallContractOperation (/app/src/rosetta-helpers.ts:595:11)\\n    at runMicrotasks (<anonymous>)\\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\\n    at getOperations (/app/src/rosetta-helpers.ts:141:23)\\n    at parseRosettaTxDetail (/app/src/api/controllers/db-controller.ts:508:22)\\n    at getRosettaBlockTransactionsFromDataStore (/app/src/api/controllers/db-controller.ts:578:23)\\n    at getRosettaBlockFromDataStore (/app/src/api/controllers/db-controller.ts:317:16)\\n    at /app/src/api/routes/rosetta/block.ts:33:21\",\"errorTag\":\"9a140353-b782-4fe4-9f67-ba8269002525\"},\"status\":500,\"req\":{\"path\":\"/block\",\"body\":{\"block_identifier\":{\"index\":80103},\"network_identifier\":{\"blockchain\":\"stacks\",\"network\":\"mainnet\"}}}}",
```
Happens when they get the latest block from status and then try to query the /block endpoint immediately afterward.

**Comment by saralab** [comment]
Awaiting v6 to confirm the fix works
