### ISSUE TITLE
Bug: failed to run mempool stats update CONNECTION_DESTROYED

### ISSUE THREAD

**Issue by zone117x** [hirosystems/stacks-blockchain-api#1852]
Just saw the following error message while running the API in a local regtest environment:

```json
{"level":"error","time":"2024-01-26T13:38:15.892Z","pid":1,"hostname":"a9c2594db67f","name":"stacks-blockchain-api","component":"core-api","err":{"type":"Error","message":"write CONNECTION_DESTROYED postgres:5490","stack":"Error: write CONNECTION_DESTROYED postgres:5490\n    at Object.execute (/stacks-api/node_modules/@hirosystems/api-toolkit/node_modules/postgres/cjs/src/connection.js:156:35)\n    at Query.handler (/stacks-api/node_modules/@hirosystems/api-toolkit/node_modules/postgres/cjs/src/index.js:294:15)\n    at Query.handle (/stacks-api/node_modules/@hirosystems/api-toolkit/node_modules/postgres/cjs/src/query.js:140:65)\n    at cachedError (/stacks-api/node_modules/@hirosystems/api-toolkit/node_modules/postgres/cjs/src/query.js:170:23)\n    at new Query (/stacks-api/node_modules/@hirosystems/api-toolkit/node_modules/postgres/cjs/src/query.js:36:24)\n    at PgWriteStore.sql (/stacks-api/node_modules/@hirosystems/api-toolkit/node_modules/postgres/cjs/src/index.js:112:11)\n    at PgWriteStore.getChainTip (/stacks-api/src/datastore/pg-store.ts:210:51)","code":"CONNECTION_DESTROYED","errno":"CONNECTION_DESTROYED","address":["postgres"],"port":[5490]},"msg":"failed to run mempool stats update"}
```

```
"failed to run mempool stats update"
"Error: write CONNECTION_DESTROYED postgres:5490
    at Object.execute (/stacks-api/node_modules/@hirosystems/api-toolkit/node_modules/postgres/cjs/src/connection.js:156:35)
    at Query.handler (/stacks-api/node_modules/@hirosystems/api-toolkit/node_modules/postgres/cjs/src/index.js:294:15)
    at Query.handle (/stacks-api/node_modules/@hirosystems/api-toolkit/node_modules/postgres/cjs/src/query.js:140:65)
    at cachedError (/stacks-api/node_modules/@hirosystems/api-toolkit/node_modules/postgres/cjs/src/query.js:170:23)
    at new Query (/stacks-api/node_modules/@hirosystems/api-toolkit/node_modules/postgres/cjs/src/query.js:36:24)
    at PgWriteStore.sql (/stacks-api/node_modules/@hirosystems/api-toolkit/node_modules/postgres/cjs/src/index.js:112:11)
    at PgWriteStore.getChainTip (/stacks-api/src/datastore/pg-store.ts:210:51)"
```

The postgres instance seems fine, so maybe a bug with the recent changes to the mempool stat debouncing.

**Comment by zone117x** [comment]
PR https://github.com/hirosystems/stacks-blockchain-api/pull/1853 may have fixed this. Haven't seen the error since.

**Comment by smcclellan** [comment]
Closing as it hasn't resurfaced. This can be reopened if it's seen again.
