### ISSUE TITLE
Chain stall with latest API release (postgres error)

### ISSUE THREAD

**Issue by wileyj** [hirosystems/stacks-blockchain-api#1917]
**Describe the bug**
stacks-blockchain version: 2.4.0.1.0
stacks-blockchain-api version: 7.9.0

this is an API instance i've been running for the last month, and recently i've hit an interesting bug. 
I noticed the API was about 1k blocks behind tip (using API version 7.8.2), and the logs were scrolling with an odd message. 
the stacks-blockchain was logging an error POSTing to the api, and the API had an interesting postgres error:
```
"MAX_PARAMETERS_EXCEEDED: Max number of parameters (65534) exceeded"
```

**To Reproduce**
1. start/restart stacks-blockchain with an API - wait a little while and it seems to trigger randomly (seems to be mempool related)

**Expected behavior**
DB write to succeed or at least move past problematic query (if mempool related, i think it should be broken apart into smaller queries or skipped altogether?)

**Console log**
Logs attached as tar.gz file 
```json
{"level":"error","time":"2024-03-30T15:45:44.155Z","pid":19,"hostname":"686ddd85793e","name":"stacks-blockchain-api","req":{"id":41378,"method":"POST","url":"/drop_mempool_tx","query":{},"params":{},"headers":{"host":"stacks-blockchain-api:3700","content-length":"7077104","content-type":"application/json"},"remoteAddress":"172.24.0.3","remotePort":35122},"component":"core-api","res":{"statusCode":500,"headers":{"x-powered-by":"Express","content-type":"application/json; charset=utf-8","content-length":"44","etag":"W/\"2c-CWv6dedCuMmupTXeq6kBI2Q6c3U\""}},"err":{"type":"Error","message":"failed with status code 500","stack":"Error: failed with status code 500\n    at onResFinished (/app/node_modules/pino-http/logger.js:110:39)\n    at ServerResponse.onResponseComplete (/app/node_modules/pino-http/logger.js:173:14)\n    at ServerResponse.emit (node:events:530:35)\n    at onFinish (node:_http_outgoing:1005:10)\n    at callback (node:internal/streams/writable:756:21)\n    at afterWrite (node:internal/streams/writable:701:5)\n    at afterWriteTick (node:internal/streams/writable:687:10)\n    at processTicksAndRejections (node:internal/process/task_queues:81:21)"},"responseTime":212,"msg":"request errored"}
{"level":"error","time":"2024-03-30T15:45:44.154Z","pid":19,"hostname":"686ddd85793e","name":"stacks-blockchain-api","component":"core-api","err":{"type":"Error","message":"MAX_PARAMETERS_EXCEEDED: Max number of parameters (65534) exceeded","stack":"Error: MAX_PARAMETERS_EXCEEDED: Max number of parameters (65534) exceeded\n    at toBuffer (/app/node_modules/@hirosystems/api-toolkit/node_modules/postgres/cjs/src/connection.js:182:20)\n    at Object.execute (/app/node_modules/@hirosystems/api-toolkit/node_modules/postgres/cjs/src/connection.js:168:20)\n    at go (/app/node_modules/@hirosystems/api-toolkit/node_modules/postgres/cjs/src/index.js:344:14)\n    at Query.handler (/app/node_modules/@hirosystems/api-toolkit/node_modules/postgres/cjs/src/index.js:333:14)\n    at Query.handle (/app/node_modules/@hirosystems/api-toolkit/node_modules/postgres/cjs/src/query.js:140:65)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at cachedError (/app/node_modules/@hirosystems/api-toolkit/node_modules/postgres/cjs/src/query.js:170:23)\n    at new Query (/app/node_modules/@hirosystems/api-toolkit/node_modules/postgres/cjs/src/query.js:36:24)\n    at PgWriteStore.sql [as _sql] (/app/node_modules/@hirosystems/api-toolkit/node_modules/postgres/cjs/src/index.js:112:11)\n    at PgWriteStore.dropMempoolTxs (/app/src/datastore/pg-write-store.ts:1812:62)","code":"MAX_PARAMETERS_EXCEEDED"},"msg":"error processing core-node /drop_mempool_tx"}
```
**Desktop (please complete the following information):**
 - OS: Debian 12
 - vCPU: 4
 - Memory: 8GB

[logs.tar.gz](https://github.com/hirosystems/stacks-blockchain-api/files/14824865/logs.tar.gz)

**Comment by wileyj** [comment]
update: postgres version is 15.4
