### ISSUE TITLE
Absence of .git-info causes API to crash

### ISSUE THREAD

**Issue by saralab** [hirosystems/stacks-blockchain-api#902]
**Describe the bug**
Absence of .git-info causes API to crash

**To Reproduce**
1. Download the latest API 
2. Delete .git-info
3. Start the API
4. API crashes with the error : 

`"{"level":"error","message":"app failed to start: Error: Git info file not found Git info file not found","stack":"Error: Git info file not found\n    at init (/stacks-api/src/index.ts:163:11)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)" `

**Expected behavior**
Ideally the absence of .gitinfo should throw a warning and proceed with the execution smoothly. Absence of .git-info shouldn't halt the API . 

**Screenshots**

**Console log**

API Logs: 
2021-12-11T21:43:21Z {"req":{"url":"/new_burn_block","headers":{"host":"10.10.0.191:3700","content-length":"310","date":"Sat, 11 Dec 2021 21:43:21 GMT","content-type":"application/json"},"method":"POST","httpVersion":"1.1","originalUrl":"/new_burn_block","query":{}},"res":{"statusCode":200},"responseTime":8,"level":"http","message":"HTTP POST /new_burn_block","timestamp":"2021-12-11T21:43:21.905Z"}
2021-12-11T21:43:24Z {"level":"error","message":"app failed to start: Error: Git info file not found Git info file not found","stack":"Error: Git info file not found\n    at init (/stacks-api/src/index.ts:163:11)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","timestamp":"2021-12-11T21:43:24.795Z"}
2021-12-11T21:43:46Z {"message":"Notice: full BNS functionality requires 'BNS_IMPORT_DIR' to be set.","level":"warn","timestamp":"2021-12-11T21:43:46.021Z"}

Stacks node logs: 
2021-12-11T21:47:08Z INFO [1639259228.113269] [src/chainstate/burn/db/sortdb.rs:1209] [chains-coordinator] PoX recipient chosen, recipient: 3JqqSxLku7h8WUD2LZ7JenoeUdNzBNEDH6, block_height: 713523
2021-12-11T21:47:20Z INFO [1639259240.280252] [src/chainstate/burn/db/sortdb.rs:3699] [chains-coordinator] ACCEPTED(713523) leader block commit b142191bd1b3144b9afa633cef1f4797787e9192c756a13db2de6439207fbe96 at 713523,36, apparent_sender: 1NGEXo4oKR563AoC2owwsb4YzGAJzUSndN

**Desktop (please complete the following information):**
 - OS: iOS
 - Version
       - stack:  2.05.0.0.0
       - Api: v0.71.2

**Comment by saralab** [comment]
@zone117x @rafaelcr  Is it a hard requirement to have  .git-info to start the API? Can we log it as a warning and move on with the API execution without stalling it completely?

**Comment by rafaelcr** [comment]
@saralab that file is currently required for the /status endpoint so it gives you the exact API version you're running. It's part of the npm build step so if you build it should generate it automatically for you

**Comment by saralab** [comment]
In that case, can we spit out this error sooner, currently it waits till the sortdb.rs module runs and the error really gets lost in the logs without a clear indication on why the API crashed.
